language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
# command to run tests
script:
  - pytest tutorial-project # or py.test for Python versions 3.5 and below
