"""Add announcement_cards table

Revision ID: abc123456789
Revises: 044e18572cbe
Create Date: 2025-07-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = 'abc123456789'
down_revision = '044e18572cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Insert default data
    announcement_cards_table = sa.table('announcement_cards',
        sa.column('title', sa.String),
        sa.column('link', sa.String),
        sa.column('image_filename', sa.String),
        sa.column('image_url', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('display_order', sa.Integer),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime)
    )
    
    op.bulk_insert(announcement_cards_table, [
        {
            'title': 'DORIS | NYC Honorary Street Names Map',
            'link': 'https://nyc.maps.arcgis.com/apps/instant/basic/index.html?appid=7c667aa2fa224684962cac5fa10ec0fd',
            'image_filename': 'street_renaming.jpg',
            'image_url': None,
            'is_active': True,
            'display_order': 1,
            'created_at': func.now(),
            'updated_at': func.now()
        },
        {
            'title': 'DORIS Public Programs',
            'link': '/posts/view/157',
            'image_filename': 'public_programs.jpeg',
            'image_url': None,
            'is_active': True,
            'display_order': 2,
            'created_at': func.now(),
            'updated_at': func.now()
        },
        {
            'title': 'Follow us on Social Media',
            'link': '/posts/view/159',
            'image_filename': 'social_media.png',
            'image_url': None,
            'is_active': True,
            'display_order': 3,
            'created_at': func.now(),
            'updated_at': func.now()
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_cards')
    # ### end Alembic commands ###