ADMINISTRATION = "Administration"
HUMAN_RESOURCES = "Human Resources"
EXTERNAL_AFFAIRS = "External Affairs"
SOCIAL_MEDIA = "Social Media"
GRANT_UNIT = "Grant Unit"
INFORMATION_TECHNOLOGY = "Information Technology"
MUNICIPAL_ARCHIVES = "Municipal Archives"
MUNICIPAL_LIBRARY = "Municipal Library"
RECORDS_MANAGEMENT = "Municipal Records Management"
EXECUTIVE = "Executive"
FACILITIES = "Facilities"

DIVISIONS = [
    ("", ""),
    (ADMINISTRATION, ADMINISTRATION),
    (HUMAN_RESOURCES, HUMAN_RESOURCES),
    (EXTERNAL_AFFAIRS, EXTERNAL_AFFAIRS),
    (SOCIAL_MEDIA, SOCIAL_MEDIA),
    (GRANT_UNIT, GRANT_UNIT),
    (INFORMATION_TECHNOLOGY, INFORMATION_TECHNOLOGY),
    (MUNICIPAL_ARCHIVES, MUNICIPAL_ARCHIVES),
    (MUNICIPAL_LIBRARY, MUNICIPAL_LIBRARY),
    (RECORDS_MANAGEMENT, RECORDS_MANAGEMENT),
    (EXECUTIVE, EXECUTIVE),
    (FACILITIES, FACILITIES),
]

ENHANCEMENT = "Enhancement"
NEW_PROJECT = "New Project"
LEGACY = "Replacement of Legacy System"

PROJECT_TYPE = [
    ("", ""),
    (NEW_PROJECT, NEW_PROJECT),
    (ENHANCEMENT, ENHANCEMENT),
    (LEGACY, LEGACY),
]

CRITICAL = "Critical"
HIGH = "High"
MEDIUM = "Medium"
LOW = "Low"

PRIORITY = [("", ""), (LOW, LOW), (MEDIUM, MEDIUM), (HIGH, HIGH), (CRITICAL, CRITICAL)]

INTERNAL = "DORIS Only"
CITYNET = "Multi-Agency"
PUBLIC = "Public"

PROJECT_ACCESS = [("", ""), (INTERNAL, INTERNAL), (CITYNET, CITYNET), (PUBLIC, PUBLIC)]

YES = "Yes"
NO = "No"
YES_NO = [("", ""), (YES, YES), (NO, NO)]
