"""added a new column path for carousel

Revision ID: 3290be942b73
Revises: 716add1c8569
Create Date: 2019-10-23 12:14:21.825755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3290be942b73'
down_revision = '716add1c8569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carousel', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('carousel', sa.Column('image_name', sa.String(), nullable=True))
    op.drop_column('carousel', 'file_name')
    op.drop_column('carousel', 'image_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carousel', sa.Column('image_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carousel', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('carousel', 'image_name')
    op.drop_column('carousel', 'file_path')
    # ### end Alembic commands ###
