"""Added Holiday Boolean Flag for Event Posts

Revision ID: 391ded4f6bf9
Revises: 044e18572cbe
Create Date: 2025-02-14 16:22:55.149067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391ded4f6bf9'
down_revision = '044e18572cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('holiday', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_posts', schema=None) as batch_op:
        batch_op.drop_column('holiday')
    # ### end Alembic commands ###
