"""Added room to user table

Revision ID: 639e1b4d8b3d
Revises: a1755712ae71
Create Date: 2018-07-27 18:36:29.720033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639e1b4d8b3d'
down_revision = 'a1755712ae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('room', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'room')
    # ### end Alembic commands ###
