"""Changed meeting_leader parameters

Revision ID: 6e3105948d8f
Revises: 9c2551c0b4d6
Create Date: 2018-08-03 14:41:38.089634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3105948d8f'
down_revision = '9c2551c0b4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'meeting_notes', 'users', ['meeting_leader'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting_notes', type_='foreignkey')
    # ### end Alembic commands ###
