"""empty message

Revision ID: 716add1c8569
Revises: cb098bd1f9c0
Create Date: 2019-10-23 10:22:35.463492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716add1c8569'
down_revision = 'cb098bd1f9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carousel', sa.Column('carousel_position', sa.Integer(), nullable=True))
    op.add_column('carousel', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('carousel', sa.Column('image_title', sa.String(), nullable=True))
    op.drop_column('carousel', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carousel', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('carousel', 'image_title')
    op.drop_column('carousel', 'file_name')
    op.drop_column('carousel', 'carousel_position')
    # ### end Alembic commands ###
