"""change post to post_type in post table

Revision ID: 9c2551c0b4d6
Revises: a1755712ae71
Create Date: 2018-07-27 18:47:28.254349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c2551c0b4d6'
down_revision = 'a1755712ae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_type', sa.Enum('News', 'Event', 'Meeting Notes', name='post_type'), nullable=True))
    op.drop_column('posts', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('type', postgresql.ENUM('News', 'Event', 'Meeting Notes', name='post_type'), autoincrement=False, nullable=True))
    op.drop_column('posts', 'post_type')
    # ### end Alembic commands ###
